<?php

function fp_preview_menu() {
    $items = array();
    
    $items['preview-pdf'] = array(
       'title' => 'Preview - Non Audio Version',
       'description' => 'Page to show the non audio preview version of the e book.',
       'page callback' => 'fp_preview_pdf',
       'access callback' => TRUE,
       'type' => MENU_CALLBACK,
    );
    $items['preview-non-audio'] = array(
       'title' => 'Preview - Non Audio Version',
       'description' => 'Page to show the non audio preview version of the e book.',
       'page callback' => 'fp_preview_non_audio',
       'access callback' => TRUE,
       'type' => MENU_CALLBACK,
    );
    
    return $items;
}


function fp_preview_pdf() {
    $output = theme("preview-pdf");
    return $output;
}


function fp_preview_non_audio() {
    drupal_add_js(drupal_get_path('module','fp_preview'). '/js/fp-preview.js');
    drupal_add_js(drupal_get_path("module", "fp_preview")."/js/jquery-ui-1.6.custom.min.js");
    drupal_add_css(drupal_get_path("module", "fp_preview")."/css/ui.all.css");
    $output = theme("preview-non-audio");
    return $output;
}



function fp_preview_block($op='list', $delta=0, $edit=array()) {
    switch($op) {
		case 'list':
			$blocks[0]['info'] = t('Email to Friend');
			$blocks[0]['cache'] = BLOCK_NO_CACHE;
			return $blocks;
		case 'view':
			$friendform = drupal_get_form('fp_preview_email_friend_form');
			$block['content'] = $friendform;
			return $block;
	}
}


function fp_preview_email_friend_form() {
    $form['to'] = array(
        '#title' => t('To Email Address'),
        '#type' => 'textfield',
        '#size' => 25,
        '#description' => t(''),
    );
    $form['from'] = array(
        '#title' => t('Your Email Address'),
        '#type' => 'textfield',
        '#size' => 25,
        '#description' => t(''),
    );
    $form['submit'] = array(
       '#type' => 'submit',
       '#value' => t('Email To Friend'),
    );
    return $form;
}


function fp_preview_email_friend_form_submit($form, &$form_state) {
    global $user;
    $to_address = $form_state['values']['to'];
    $from_address = $form_state['values']['from'];
    $subject = "The Fingerprince Preview";
    $params['account'] = $user;
    $params['to_address'] = $to_address;
    $params['email_body'] = '';
    $params['subject'] = $subject;
    log_debug("To address is [$to_address]");
    log_debug("From address is [$from_address]");
    drupal_mail('fp_preview', 'emails', $to_address, user_preferred_language($user), $params, $from_address); 
    drupal_set_message("Your email has been sent to " . $to_address . ".");
}



function fp_preview_mail($key, &$message, $params) {
    $language = $message['language'];
    $variables = user_mail_tokens($params['account'], $language);
    switch ($key) {
        case 'emails':
            $boundary = '----=_NextPart_'.md5(uniqid());
            $message['headers']['Content-Type'] = "text/html; charset=utf-8; boundary=\"$boundary\"";
            $message['subject'] = $params['subject'];
            $body_text = create_email_body($params['email_body'], $boundary);
            $path = isset($_GET['q']) ? $_GET['q'] : '<front>';
            $link = url($path, array('absolute' => TRUE));
            $message['body'][] = "A friend has invited you to view a preview of The Fingerprince. Click <a href='" . $link . "'>here</a> to view.";
            break; 
    }
}




function fp_preview_theme() {
    return array(
       'preview-pdf' => array(
            'template' => 'preview-pdf',
            'arguments' => array(),
        ),
       'preview-non-audio' => array(
            'template' => 'preview-non-audio',
            'arguments' => array(),
        ),
    );
}